name: Coding Style

on:
    pull_request: ~

jobs:
    coding-style:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  coverage: none
            - name: php-cs-fixer
              run: |
                  wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v3.13.2/php-cs-fixer.phar -q
                  php php-cs-fixer.phar fix --dry-run --diff
