name: Unit Tests

on:
    pull_request: ~
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    tests:
        name: Unit Tests
        runs-on: ubuntu-latest

        strategy:
            matrix:
                include:
                    - php: '8.2'
                      symfony: '6.2'
                      mode: low-deps
                      deprecations_helper: max[self]=0

                    - php: '8.1'
                      symfony: '6.2'
                      mode: high-deps
                      deprecations_helper: disabled=1

            fail-fast: false

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "${{ matrix.php }}"
                  coverage: none
                  ini-values: date.timezone=UTC,memory_limit=-1,session.gc_probability=0,apc.enable_cli=1,zend.assertions=1

            - name: Install dependencies
              run: |
                  composer require --no-update --dev symfony/phpunit-bridge=${{ matrix.symfony }} symfony/yaml=${{ matrix.symfony }}
                  
                  if [[ "${{ matrix.mode }}" = low-deps ]]; then
                      composer update --prefer-dist --no-interaction --no-ansi --no-progress --prefer-lowest
                  else
                      composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  fi

            - name: Run tests
              run: SYMFONY_DEPRECATIONS_HELPER="${{ matrix.deprecations_helper }}" php vendor/bin/simple-phpunit
